# version: "3"
services:
  chrome:
    platform: linux/x86_64
    image: selenium/node-chrome:beta
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=20 # タイムアウトを20秒に設定

  edge:
    platform: linux/x86_64
    image: selenium/node-edge:beta
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=20 # タイムアウトを20秒に設定

  firefox:
    platform: linux/x86_64
    image: selenium/node-firefox:beta
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=20 # タイムアウトを20秒に設定

  selenium-hub:
    platform: linux/x86_64
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
  python-container:
    build: 
      context: ./python
      args:
        passwd: passwd
    image: selenium-python
    container_name: selenium-python-container
    working_dir: "/home/pybatch/python"
    tty: true
    volumes:
      - ./python:/home/pybatch/python
